FROM ubuntu:22.04

COPY sources.list /etc/apt/sources.list

RUN apt update && apt install -y openssh-server sudo -y

RUN apt install -y git wget python3-pip fish curl

COPY authorized_keys /root/.ssh/authorized_keys

RUN chmod 700 /root/.ssh && chmod 600 /root/.ssh/authorized_keys

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN chsh -s /usr/bin/fish

RUN service ssh start

EXPOSE 22

RUN mkdir -p ~/miniconda3 &&\
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh &&\
    bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3 &&\
    rm -rf ~/miniconda3/miniconda.sh

RUN ~/miniconda3/bin/conda init fish &&\
    ~/miniconda3/bin/conda init bash

ENV PATH=/root/miniconda3/bin:${PATH}

RUN conda create -n torch python=3.12 -y 

SHELL ["conda", "run", "-n", "torch", "/bin/bash", "-c"]

RUN pip install torchtune

CMD ["sh","-c","/usr/sbin/sshd -D"]


